// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type GoqueueJobStatus string

const (
	GoqueueJobStatusAvailable GoqueueJobStatus = "available"
	GoqueueJobStatusRunning   GoqueueJobStatus = "running"
	GoqueueJobStatusFailed    GoqueueJobStatus = "failed"
	GoqueueJobStatusFinished  GoqueueJobStatus = "finished"
)

func (e *GoqueueJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GoqueueJobStatus(s)
	case string:
		*e = GoqueueJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GoqueueJobStatus: %T", src)
	}
	return nil
}

type NullGoqueueJobStatus struct {
	GoqueueJobStatus GoqueueJobStatus `json:"goqueue_job_status"`
	Valid            bool             `json:"valid"` // Valid is true if GoqueueJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGoqueueJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GoqueueJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GoqueueJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGoqueueJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GoqueueJobStatus), nil
}

type GoqueueRetryPolicy string

const (
	GoqueueRetryPolicyConstant    GoqueueRetryPolicy = "constant"
	GoqueueRetryPolicyLinear      GoqueueRetryPolicy = "linear"
	GoqueueRetryPolicyExponential GoqueueRetryPolicy = "exponential"
)

func (e *GoqueueRetryPolicy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GoqueueRetryPolicy(s)
	case string:
		*e = GoqueueRetryPolicy(s)
	default:
		return fmt.Errorf("unsupported scan type for GoqueueRetryPolicy: %T", src)
	}
	return nil
}

type NullGoqueueRetryPolicy struct {
	GoqueueRetryPolicy GoqueueRetryPolicy `json:"goqueue_retry_policy"`
	Valid              bool               `json:"valid"` // Valid is true if GoqueueRetryPolicy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGoqueueRetryPolicy) Scan(value interface{}) error {
	if value == nil {
		ns.GoqueueRetryPolicy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GoqueueRetryPolicy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGoqueueRetryPolicy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GoqueueRetryPolicy), nil
}

type GoqueueJob struct {
	JobID        int32              `json:"job_id"`
	QueueName    string             `json:"queue_name"`
	CreatedAt    pgtype.Timestamp   `json:"created_at"`
	StartedAt    pgtype.Timestamp   `json:"started_at"`
	FinishedAt   pgtype.Timestamp   `json:"finished_at"`
	ScheduledAt  pgtype.Timestamp   `json:"scheduled_at"`
	MaxRetries   int32              `json:"max_retries"`
	RetryAttempt int32              `json:"retry_attempt"`
	RetryPolicy  GoqueueRetryPolicy `json:"retry_policy"`
	Status       GoqueueJobStatus   `json:"status"`
	Error        pgtype.Text        `json:"error"`
	Arguments    []byte             `json:"arguments"`
	Metadata     []byte             `json:"metadata"`
}

type GoqueueQueue struct {
	QueueName string           `json:"queue_name"`
	IsFifo    bool             `json:"is_fifo"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
