// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	FetchJobLocked(ctx context.Context) (GoqueueJob, error)
	InsertJob(ctx context.Context, arg InsertJobParams) (GoqueueJob, error)
	RescheduleJob(ctx context.Context, arg RescheduleJobParams) (GoqueueJob, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (GoqueueJob, error)
	UpdateJobFailed(ctx context.Context, arg UpdateJobFailedParams) (GoqueueJob, error)
	UpdateJobFinished(ctx context.Context, jobID int32) (GoqueueJob, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (GoqueueJob, error)
}

var _ Querier = (*Queries)(nil)
