// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	InsertJob(ctx context.Context, arg InsertJobParams) (Job, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
