// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	GetJob(ctx context.Context) (GoqueueJob, error)
	InsertJob(ctx context.Context, arg InsertJobParams) (GoqueueJob, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (GoqueueJob, error)
}

var _ Querier = (*Queries)(nil)
